### ISSUE TITLE
Bot-powered ACES are a MS Teams based solution; SPFx not involved, correct?

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/Bot-Powered-ACE-Preview#52]
From earlier discussions about this feature, it was implied that this would be a new option within an SPFx ACE project, but looking at the labs, it looks like it isn't related to SPFx at all... is that correct?

Instead, it looks like it's more of a Microsoft Teams app defined within the new `dashboardCards` array within the Teams app's manifest.json file.

Do I have this correct, or am I missing something?

If I'm correct, makes sense as a bot-powered solution requires a web service and since SPFx is 100% client-side, it wouldn't make sense to have it defined using SPFx.

**Comment by lucabandMSFT** [comment]
hey @andrewconnell ,
yes, you got it 100% right.

As there's no JAvascript code needed. No SPPKG files are created. Instead, a Teams package is the only "artefact" required so that the card can show up in the card picker.

**Comment by VesaJuvonen** [comment]
Closing as answered.
