### ISSUE TITLE
Question: Update to align with Bot Builder latest 4.20.0

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/Bot-Powered-ACE-Preview#61]
Hi

Just curious, was looking to bring a Teams Toolkit bot with Teams AI Library (for experimentation/learning/geeking out) into Viva Connections ACEs,  just wondering if there any plans to update to align the versions? Just noticed that the later ones have security updates etc.

Also, are the any plans to continue investing here?  This repo was pretty hard to find, only via a single blog post.

**Comment by VesaJuvonen** [comment]
thx @pkbullock for the interest around this preview program. We will be definitely updating to the latest versions of the Bot Builder which will be available as we get closer on the public release. We have now closed the preview program as we got great input from attendees and are now applying significant changes on the models. 

As we pause the preview program, will close this one as well. Thanks for your input and looking forward on the awesome scenarios with the Teams AI library as we get things published 👍
